version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    expose:
      - "5678"
    env_file:
      - n8n.env
    volumes:
      - n8n:/home/node/.n8n
    networks:
      - default
      - web
    # Generate self-sign and proxy from cloudflare
    labels:
      - traefik.http.routers.n8n.service=n8n
      - traefik.http.routers.n8n.rule=Host(`n8n.do.co.th`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.services.n8n.loadbalancer.server.port=5678
  db:
    restart: always
    image: postgres:16
    env_file:
      - db.env
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    networks:
      - default
    labels:
      - traefik.enable=false

# persistant volume
volumes:
  n8n:
  db:

networks:
  default:
  # network to trafik
  web:
    external: true