version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.77.2
    restart: always
    env_file:
      - ./config/n8n/n8n.example2.env
    ports:
      - 5678:5678
    volumes:
      - ./n8n-data:/home/node/.n8n

  traefik:
    image: traefik:v3.3.3
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik-data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  n8n-data:
  traefik-data: