version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.77.2
    restart: always
    env_file:
      - ./config/n8n/n8n.example2.env
    ports:
      - 5678:5678
    volumes:
      - ./n8n-data:/home/node/.n8n

volumes:
  n8n-data: