version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.77.2
    restart: always
    environment:
      # *** General ***
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_ENV=production
      # *** Settings ***
      - N8N_SECURE_COOKIE=false
    ports:
      - 5678:5678
    volumes:
      - ./n8n-data:/home/node/.n8n

volumes:
  n8n-data: